name: Build CyberCafe POS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Android platform
        run: flutter create --platforms=android .

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CyberCafePOS-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Windows platform
        run: flutter create --platforms=windows .

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: CyberCafePOS-windows-exe
          path: build/windows/x64/runner/Release/
